### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by alexandernst** [captain-fox/airpress#1]
Hi! We've noticed that the function `pkcs7_sign` located at https://github.com/captain-fox/airpress/blob/master/airpress/crypto.py is an exact copy of https://github.com/Develatio/django-walletpass/blob/master/django_walletpass/crypto.py

Please follow the guidelines of our License ( https://github.com/Develatio/django-walletpass/blob/master/LICENSE ), specifically Pn. 1 

Regards

**Comment by captain-fox** [comment]
Yes, I've copied it from your package and explicitly notified you about this here:
https://github.com/Develatio/django-walletpass/issues/1#issuecomment-626663343

From text of license I can't really understand what am I supposed to copy and where. Can you please clear this out?

**Comment by alexandernst** [comment]
Add a comment at the top of the file, referencing the company / repo from which the code was copied.

**Comment by captain-fox** [comment]
@alexandernst I have added IP reference as you've requested. Please check out contents of https://github.com/captain-fox/airpress/blob/master/airpress/crypto.py 
Will this do?

Though it would be really nice of you to change your own license to MIT (at least for `crypto.py`) so this package can remain 100% MIT.

I'm doing back-end work with pyramid, so the goal of this tiny tool is to allow to create `pkpass` files in an easy way independently from framework you're using.

**Comment by alexandernst** [comment]
Yes, that works for us. Thank you!

Our license is a MIT sublicense. You're only required to mention us when using our library. We open sourced the library after investing time in it. We keep it up to date. We fix bugs and provide support. It sounds reasonable for us to require our users to give some credits to our work, don't you think?

**Comment by captain-fox** [comment]
@alexandernst makes perfect sense. Thanks for the explanation!
